### PR TITLE
Moved cli command to bin directory

### PR DESCRIPTION
**Pull request by core23**
- Moved cli command to bin directory
- Renamed command to ``shariff``, because ``index.php`` is the worst name if you have other commands

This is a BC break.

### CODE REVIEW

**Comment by liayn** [comment]
Maybe I understand that wrong, but the current index.php is not meant to be used as cli script,  right?

**Comment by core23** [comment]
Can you name the purpose of the file? It's defined as a composer binary @liayn

**Comment by liayn** [comment]
Hm... indeed. Wasn't aware of that. Does that make sense at all?
I mean this is a demo file how to use the API, which is meant to be called via AJAX? So the CLI context does not make sense to me.

**Comment by compeak** [comment]
`index.php` was never meant as a CLI command (and I do not know why it is listed as such). Furthermore it is not only a demo on how to use the API, but also the way everybody who just downloads a release and puts the files onto rented webspace makes use of the backend.

Removing this file would break that.

If you want to remove this file, you need to suggest a way to do it that does not disable this use case.

**Pull request closed without merging**
