### PR TITLE
proper url encoding

### PR DESCRIPTION
**Pull request by hokascha**
Added urlencode() to the url to allow hash fragments in urls like http://example.com/#target
Makes facebook counts working if url has hashes.

### CODE REVIEW

**Comment by liayn** [comment]
This looks rather strange and would be a breaking change, since the input is now expected to be urlencoded.
Can you explain why you need to do that at all?

**Comment by hokascha** [comment]
Sure, try getting counts from facebook for an URL that has a hash fragment at the end, for example: http://yourdomain.com/page#target
This will break the facebook api call when using access tokens because the access token is appended to the (unescaped) url. The result is a API call like this: 
https://graph.facebook.com/v2.2/?id=http://yourdomain.com/page#target&access_token=12345...
In the end, the access token is not transmitted to facebook because it is now part of the hash fragment. The URL really should be escaped. Even if you swap the url and access_token parameters in the API call, the hash fragment would still not be transmitted to facebook.

**Comment by hokascha** [comment]
To prevent braking changes, you could just urlencode the url in BackendManager.php not in index.php.

**Comment by liayn** [comment]
This must be handled in the services and not in the BackendManager!
Each service must ensure that the called URL to retrieve stats are valid, that's not the job of the upstream API layers.

**Comment by liayn** [comment]
Will you create a new pull request?

**Comment by hokascha** [comment]
Just a moment ;-)

**Comment by liayn** [comment]
You can push your new solution over to this pr actually (force push to your branch)

**Pull request closed without merging**
