### PR TITLE
[TASK] Update guzzle and phpunit dependencies

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by compeak** [comment]
@liayn Looks like we need to drop support for PHP < 7.1 for this, right?

**Comment by liayn** [comment]
@compeak I will adjust `"php": "^5.6 || ^7.0"` somehow to require v5 and v7 support

**Comment by liayn** [comment]
not sure why the lint tests failed now with git clone issue. can you please check @compeak

**Comment by compeak** [comment]
@liayn Probably because Travis does not set secret variables (GitHub API token) when running builds triggered by pull requests for security reasons.

**Comment by compeak** [comment]
@liayn It won't work. Travis doesn't want code contained in pull requests to be able to exfiltrate secrets.

The lint step succeeded on my machine, so I merged it. Thanks.

**Pull request merged**
