### PR TITLE
Updated zend dependency

### PR DESCRIPTION
**Pull request by core23**
Only the zend cache is used.

### CODE REVIEW

**Comment by liayn** [comment]
composer.lock must be committed too

**Comment by liayn** [comment]
Does not work as your zend requirement raises the min PHP version to 5.5. See zend-cache 2.5.2
(zend devs messed up semver here)

I fixed this with https://github.com/heiseonline/shariff-backend-php/pull/55
(I know it's not nice to list them all, but we need to nail all those version if we want to keep the 5.4 support)

**Comment by core23** [comment]
IMO that's no problem as php version 5.4 is no supported anymore (https://github.com/heiseonline/shariff-backend-php/pull/60)

**Comment by compeak** [comment]
Thank you.

**Pull request merged**
