### PR TITLE
Remove LinkedIn share count API

### PR DESCRIPTION
**Pull request by richard67**
Pull request for issue #158 .

In February 2018, LinkedIn announced that their Share button will not show any counts anymore, and the API to fetch counts from also has been closed.

See announcement here: [https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter](https://developer.linkedin.com/blog/posts/2018/deprecating-the-inshare-counter) .

This pull request (PR) here removes the LinkedIn service from Shariff Backend PHP for the reasons stated above, like it had to be done in past with GooglePlus and Twitter for the same reasons (abandoned counting by the provider).

How to test: By code review, or set up a backend and check that the LinkedIn service is not available anymore.

### CODE REVIEW

**Comment by richard67** [comment]
@compeak or other maintainers: This is not a BC break so I don't think it needs a new major version for a release, new minor version should be sufficient.

I will soon make a PR to remove the share counts for LinkedIn from the dummy backend (json file) used in the Shariff demo.

**Comment by vkhramtsov** [comment]
@richard67 @compeak Any news here?

**Comment by richard67** [comment]
@vkhramtsov I am not a maintainer of this repository, I am only contributor, so I can’t decide when this pull request will be merged. But you can simply remove the LibkedIn service from index.php of your Shariff PHP backend, then the 404 error should disappear.

**Comment by compeak** [comment]
Thanks.

**Comment by vkhramtsov** [comment]
@richard67 @compeak Thank you

**Pull request merged**
