### PR TITLE
[TASK] Raise version constraint for friendsofphp/php-cs-fixer

### PR DESCRIPTION
**Pull request by josefglatz**
PHP 7.2 tests can't succeed otherwise

To update composer dependencies, the following command was used:
`composer require friendsofphp/php-cs-fixer --dev`

Fixes: #140

### CODE REVIEW

**Comment by liayn** [comment]
Travis fails due to php-cs-fixer requiring PHP7.1 now.

I actually ask the question here: Should the php-cs-fixer really be included in the composer.json? It is thereby bound to the platform requirements of the product.
IMO php-cs-fixer is a dev-tool (which accidentally is written in PHP), but has no dependency to the product at all.

**Comment by josefglatz** [comment]
So you would better exclude php-cs-fixer in conposer.json and adopt Travis-CI script?



Diese Nachricht wurde von meinem Smartphone versandt

**Comment by liayn** [comment]
Yes. @compeak What do you think?

**Comment by compeak** [comment]
> So you would better exclude php-cs-fixer in composer.json and adopt Travis-CI script?

I'm working on this.

**Comment by compeak** [comment]
@josefglatz @liayn I removed `php-cs-fixer` from the composer files and moved it into a separate lint step in Travis CI.

**Comment by josefglatz** [comment]
@liayn @compeak so we can close this PR?

**Comment by compeak** [comment]
Yes.

**Pull request closed without merging**
