### PR TITLE
[BUGFIX] Update Facebook API access

### PR DESCRIPTION
**Pull request by liayn**
Use API version 2.8 and kick old FQL query.

#120, #121

### CODE REVIEW

**Comment by liayn** [comment]
@compeak how do I fix codeclimate?? Change config or make the codes simpler (which I doubt)?

**Comment by compeak** [comment]
@liayn I don't know how to simplify the code either. So a codeclimate config change seems to be necessary.

**Comment by liayn** [comment]
@compeak finally managed to change the code around. all green ;-)

**Comment by compeak** [comment]
Thank you.

**Pull request merged**
