### PR TITLE
Remove GooglePlus share count API

### PR DESCRIPTION
**Pull request by richard67**
Pull request for issue #131 .

In June 2017, Google announced that their Share button will not show any counts anymore in order to speed up loading.

See announcement here: [https://plus.google.com/110610523830483756510/posts/Z1FfzduveUo](https://plus.google.com/110610523830483756510/posts/Z1FfzduveUo).

See also discussion on stackoverflow here: [https://stackoverflow.com/questions/45157191/google-share-counts-are-not-showing](https://stackoverflow.com/questions/45157191/google-share-counts-are-not-showing).

You can verify at the online generators for the sharing and the plusone button that none of them shows any counts:
[https://developers.google.com/+/web/share/](https://developers.google.com/+/web/share/)
[https://developers.google.com/+/web/+1button/](https://developers.google.com/+/web/+1button/)

Any website which I have seen since that time which use Shariff with backend and where the backend obviously works well, like e.g. [http://ct.de/-2467514](http://ct.de/-2467514) (see Shariff at the bottom) shows a value of zero for the GooglePlus counter.

So it seems also the PHP API for getting the counts has been abandoned by Google.

This pull request (PR) here removes the GooglePlus service from Shariff Backend PHP for the reasons stated above, like it had to be done a while ago with Twitter for the same reasons (abandoned counting by the provider).

How to test: By code review, or set up a backend and check that the GooglePlus service is not available anymore.

### CODE REVIEW

**Comment by compeak** [comment]
@richard67 @liayn Should these changes require a major release?

(I am asking this because of the past difficulties with release classifications.)

**Comment by liayn** [comment]
IMO it's not a breaking change, unless the thing crashes if Google is still in the list of services in the configuration. If superfluous elements the configuration do not cause problems then this is non-breaking.

**Comment by richard67** [comment]
I can't decide about releases since I am only a free contzributor and not a maintainer.

**Comment by richard67** [comment]
@compeak @liayn I've just tested here and found following:

If the service `GooglePlus` is included in the `services` array in index.php and the GooglePlus.php has been removed, and the frontend uses the googleplus button, then no other services' counters are displayed at all, and (if error logging on) you find in your PHP error log 2 warnings about the missing file, and then 1 fatal PHP error about the exception being unhandled.

As soon as you remove the service `GooglePlus` from in the `services` array in index.php, all other counters are shown correctly after page reload.

So yes, it seems to be some kind of a bc break, but this is caused by the incomplete error handling of the backend, which's improvement should be subject of another pull request. In general problems for 1 service (e.g. wrong Facebook stuff in config) should not stop the complete thing, other services should be still processed after such a problem.

On the other hand it is not really a bc break because no interface has changed, same URL parameters for query, same format of returned json.

Therefore I think from a formal point of view this PR here does not require a new major version number, it would be ok to do a 7.2.0, but from a practical point of view it could make sense to do an 8.0.0 to better notify users about having to change their index.php if they are using the GooglePlus service.

I leave the final decision to the maintainers.

**Comment by compeak** [comment]
> So yes, it seems to be some kind of a bc break, but this is caused by the incomplete error handling of the backend, which's improvement should be subject of another pull request. In general problems for 1 service (e.g. wrong Facebook stuff in config) should not stop the complete thing, other services should be still processed after such a problem.

I will do a major release then.

Thank you.

**Comment by compeak** [comment]
@richard67 @liayn I believe [this](https://github.com/heiseonline/shariff-backend-php/commit/d607c7ccf67e35ffe62d4903b449e71d8048731c) should fix the empty results problem.

**Comment by richard67** [comment]
@compeak Your commit looks correct for me, but it does not change the behavior I described above. The unhandled exception I mentioned in my previous post is raised in line 68 of ServiceFactory.php (i.e. the `new $serviceClass` statement) when GooglePlus.php is removed but the service is still used in index.php.

See the PHP error log:
```
[06-Feb-2018 20:26:16 Europe/Berlin] PHP Warning:  include(/htdocs/shariff-backend-php/vendor/composer/../../src/Backend/GooglePlus.php): failed to open stream: No such file or directory in /htdocs/shariff-backend-php/vendor/composer/ClassLoader.php on line 444
[06-Feb-2018 20:26:16 Europe/Berlin] PHP Warning:  include(): Failed opening '/htdocs/shariff-backend-php/vendor/composer/../../src/Backend/GooglePlus.php' for inclusion (include_path='.:/usr/lib/php7.1') in /htdocs/shariff-backend-php/vendor/composer/ClassLoader.php on line 444
[06-Feb-2018 20:26:16 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Heise\Shariff\Backend\GooglePlus' not found in /htdocs/shariff-backend-php/src/Backend/ServiceFactory.php:68
Stack trace:
#0 /htdocs/shariff-backend-php/src/Backend/ServiceFactory.php(46): Heise\Shariff\Backend\ServiceFactory->createService('GooglePlus', Array)
#1 /htdocs/shariff-backend-php/src/Backend.php(49): Heise\Shariff\Backend\ServiceFactory->getServicesByName(Array, Array)
#2 /htdocs/test1/shariff-backend-demo/index.php(52): Heise\Shariff\Backend->__construct(Array)
#3 /htdocs/test1/shariff-backend-demo/index.php(60): Application::run()
#4 {main}
  thrown in /htdocs/shariff-backend-php/src/Backend/ServiceFactory.php on line 68
```

I think it would make sense to wrap line 68 of ServiceFactory.php into a "try .. catch" block and just log some error in case if the class creation fails. I can make a PR for that if nobody else wants to, but I would like to know your opinion (@compeak @liayn ...).

**Comment by compeak** [comment]
> Your commit looks correct for me, but it does not change the behavior I described above.

It looks like I fixed something else.

> I think it would make sense to wrap line 68 of ServiceFactory.php into a "try .. catch" block and just log some error in case if the class creation fails.

Sounds good.

**Comment by richard67** [comment]
@compeak 

>  It looks like I fixed something else.

Well, it seems your fix made the backend be much faster.

> Sounds good.

Hmm, it seems to be not as easy as I thought. I am working on it, but my idea does not work (yet).

**Comment by richard67** [comment]
@compeak @liayn Check my new PR #135 for solving the problem with the PHP error in case if a service does not exist but is configured to be used.

**Comment by richard67** [comment]
@compeak @liayn New PR #136 replaces PR #135 mentioned above.

**Comment by richard67** [comment]
@compeak PR #137 is better, so I closed mine.

**Pull request merged**
