### PR TITLE
implement facebook share count via graph api id method

### PR DESCRIPTION
**Pull request by uwej711**
see issue #13, this is a first proposal to fix this. Needs some documentation; couldn't run the tests locally, will check travis.

### CODE REVIEW

**Comment by devimplode** [comment]
Thanks.
I generalized the most functions, added an config example, generated a new build and checked Travis.
But I'm with pr #14 far ahead. It would take a while to merge back to `heiseonline:master`.
Maybe @pmb0 pulls #14 soon or you'd merge it into your branch directly.
devimplode/shariff-backend-php@9a2f18a9e2203a2a1a907b74739e4764225cc871

PS: What Guzzle version did you use? Mine didn't have ```Request::send()```
PPS (also @pmb0): does someone has a nice idea for checking if variables are present in arrays (maybe very deep). It sucks to check every config level!

**Comment by uwej711** [comment]
Sorry about that Guzzle thing,I backported this to have it running with PHP 5.3 using Guzzle 3.8.x, there the send method exists. Currently I have no test environment for the latest guzzle version, but I think it's better to set one up.

**Comment by pmb0** [comment]
Hi @uwej711, thank you for your changes. Can you provide some docs and unit test for the new feature?

**Comment by uwej711** [comment]
Hi @pmb0, yes I will do that in the next days!

**Pull request merged**
