### PR TITLE
Optimize composer.json file

### PR DESCRIPTION
**Pull request by core23**
- Replaced tabs with whitespace
- Use global caret notation instead of greater or tilde notation (see: https://getcomposer.org/doc/articles/versions.md)
- Require stable PHP releases. There is no PHP 6 release!
- Sort dependencies

### CODE REVIEW

**Comment by liayn** [comment]
This one needs a rebase.

**Comment by compeak** [comment]
Since this drops `zend-son` it cannot be merged until issue #56 has been resolved.

**Comment by core23** [comment]
Rebased

**Comment by liayn** [comment]
The error is due to the missing cleanup #109.

**Comment by compeak** [comment]
#108 and #109 have been merged.

**Comment by core23** [comment]
Both PRs were merged :)

**Comment by compeak** [comment]
Thanks.

**Pull request merged**
