### PR TITLE
Cleaner

### LINKED ISSUE #37: Überflüssige Dateien und Ordner entfernen.
Schön wäre eine entschlackte Version des Builds. Allein der Docs Ordner in guzzle sind bei mir ca. 400kb. Ich schätze mal, das wenn man einige der überflüssigen sachen entfernen könnte, man die hälfte der ursprünglichen Dateigröße hätte.

### PR DESCRIPTION
**Pull request by craiq**
Delete all unused files in the vendor folder - fix #37

how to use:
* run install cleaner.sh
* run clean.sh
* run build.sh

reduces the size by around 40%

### CODE REVIEW

**Comment by core23** [comment]
Don't like the idea to have vendor stuff in the repository and have to remove it after I downloaded it by composer

**Comment by craiq** [comment]
Guess you are changing your files directly in the build folder, what's not supposed to be.

my way (guess how it's supposed to be)
* install [composer](https://getcomposer.org/)
* clone the repo
* make the changes in the src folder
* run ```composer install``` in the repo folder
* (run ```composer update```)
* (run clean.sh)
* run build.sh

with ```composer install``` you will get a vendor folder in your repo. This one is copied in the build folder when running build.sh.

**Comment by craiq** [comment]
why you have to remove it?
just use the files from the build folder after you run build.sh

**Comment by craiq** [comment]
don't work with new build prozess anymore

**Pull request closed without merging**
