### PR TITLE
[FEATURE] Use latest guzzle version

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by liayn** [comment]
I fixed the PHP 7 phpcs issue, but the hhvm issue is probably not fixable, as guzzle itself fails with the same problem on hhvm: https://travis-ci.org/guzzle/guzzle/jobs/105956568#L331

In general I'm very convinced that hhvm will loose importance again now with PHP 7 being available. At least we just removed hhvm from our servers again and changed back to nativ PHP.

So the questions now is: Declare the next shariff-backend to not be compatible with hhvm, or drop the upgrade to guzzle 6.1.x?

**Comment by liayn** [comment]
Last version declares hhvm as "allowed to fail".

**Comment by liayn** [comment]
Fixes: https://github.com/heiseonline/shariff-backend-php/issues/44

**Comment by compeak** [comment]
Thanks a lot, @liayn and @core23.
(Please do not do that exclamation mark thing...)

**Comment by liayn** [comment]
@compeak The exclamation mark thingy is actually extremely useful. It indicates commits which contain breaking changes. Generally I would suggest to switch to a more structured commit message format.
Take a look at: https://wiki.typo3.org/CommitMessage_Format_%28Git%29

**Comment by compeak** [comment]
> Generally I would suggest to switch to a more structured commit message format.

Yes.

It is time to create contribution guidelines. I need to do some research.

**Comment by compeak** [comment]
I started collecting guidelines [here](https://gist.github.com/compeak/0c93293893f094a0a523).

**Comment by core23** [comment]
Thank you for your help @liayn

**Pull request merged**
